export const LOCATION_FILTER = {
  enabled: true,
  location: "Massachusetts",
  displayName: "MA Jobs",
  exactStatePatterns: [
    ", MA",
    " MA,",
    " MA ",
    "(MA)",
    "Massachusetts",
  ],
  cityPatterns: [
    "Boston",
    "Cambridge",
    "Somerville",
    "Quincy",
    "Worcester",
    "Springfield",
    "Lowell",
    "Brookline",
    "Newton",
    "Waltham",
    "Medford",
    "Malden",
    "Framingham",
    "Natick",
    "Wellesley",
    "Needham",
    "Burlington",
    "Lexington",
    "Andover",
    "Woburn",
  ],
};
